_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 41
                - 55
                - 100
            "2":
                - 1
                - 41
                - 55
                - 100
            "3":
                - 23
                - 55
            "4": 3.10.0
            "5": 0.19.6
            "8":
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
amp:
    value: false
batch_size:
    value: 1
epochs:
    value: 5
img_scale:
    value: 0.5
learning_rate:
    value: 1e-05
save_checkpoint:
    value: true
val_percent:
    value: 0.1
